config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  root 'home#index'
  get 'about', to: 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :friends
end

#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show] #otherwise generate error user Id will not be there, called by d
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /friends or /friends.json
  def index
    flash.now.notice = "Please sign in to create your custom friend list!" if !user_signed_in?
    if params[:q].blank? 
      @friends = Friend.all
    else
      @term = params[:q]
      @friends = Friend.where('first_name LIKE ?', '%'+params[:q]+'%')
    end  
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    
    # if @friend.save
    #     redirect_to @friend, notice: "Friend was successfully created."  
    # else
    #     render 'new'
    # end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[ :id])
    redirect_to friends_path, notice: "You are not authorized for this action!" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="field mb-3"> 
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
    <br/>
  <div class="actions">
    <%= form.submit class: "btn btn-dark"%>
  </div>
<% end %>

app/views/friends/edit.html.erb
<br/>
<h1 style="margin: auto; width: 22%; padding: 2rem; background: #F8F8F8; border-radius: 50px">Edit friend</h1>

<%= render 'form', friend: @friend %>

<br/>

<%= link_to 'Show', @friend, class: "btn btn-dark" %> |
<%= link_to 'Back', friends_path, class: "btn btn-dark"%>

app/views/friends/index.html.erb
<br/>
<h1 style="margin: auto; width: 22%; padding: 2rem; background: #F8F8F8; border-radius: 50px">List of Friends</h1>
<br/>

<table class="table table-striped table-hover table-bordered ">
  <thead class="table-dark">
    <tr align="Center">
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>User ID</th>
      <th colspan="3">Operations</th>
      


    </tr>
  </thead>

  <tbody align="Center">   
    <% @friends.each do |friend| %>
    <%if friend.user == current_user%>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.user_id %></td>
        <td><%= link_to 'Show', friend, class:"btn btn-outline-primary btn-sm" %></td>

        <%if user_signed_in?%>
          <td><%= link_to 'Edit', edit_friend_path(friend), class:"btn btn-outline-success btn-sm" %></td>
          <td><%= link_to 'Delete', friend, class:"btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>
<br>


<%if user_signed_in?%>
  <%= link_to 'Add a New friend', new_friend_path, class: "btn btn-dark" %>
<%end%>

app/views/friends/new.html.erb
<br/>
<h1 style="margin: auto; width: 26%; padding: 2rem; background: #F8F8F8; border-radius: 50px">Add a new friend</h1>

<%= render 'form', friend: @friend %> 
<br/>
<%= link_to 'Back', friends_path, class: "btn btn-dark" %>

app/views/friends/show.html.erb
<br/>

<div style="background-color: #E8E8E8; border-radius: 20px; padding: 2rem;" class="container">
  <p>
    <strong>First name:</strong>
    <%= @friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @friend.phone %>
  </p>
  
    <%= link_to 'Edit friend', edit_friend_path(@friend), class: "btn btn-dark" %> | 
    <%= link_to 'Destroy', @friends, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %> |

     
<%= link_to 'Back to list', friends_path, class: "btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to 'Friend list', friends_path, class: "nav-link" %>
        </li>   
        <% if user_signed_in? %>
           <li class="nav-item">
          <%= link_to 'Add friend', new_friend_path, class: "nav-link" %>
        </li> 
          <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li> 
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
            </li> 
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li> 
        <%end%>
        
      </ul>
      <!-- <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
      <%= form_with url: friends_path, method: 'get' ,class:  "d-flex" ,local: true do |form| %>
        <%= form.text_field :q, class: 'form-control', placeholder: 'Search....', autofocus: true, value: @term %>
        <%= button_tag :Search, class: "btn btn-outline-success" %>
        <%end%>
    </div>
  </div>
</nav> 

app/views/home/about.html.erb
<br>
<h1 align="Center">About us</h1>

<p align="Center">This website is still in the development phase...</p>

app/views/home/index.html.erb
<h1 align="Center" style="margin-top: 17rem;">Welcome! This is a friends Management application</h1>

<div align="Center">
	<%if !user_signed_in? %>
	<%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-dark" %>
	<%= link_to 'Sign In', new_user_session_path, class: " btn btn-dark" %>
	<%end%>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Myfriends</title>
  </head>
  <body>
    <%= render 'home/header'%>
    <%if notice %>
        <%= render 'layouts/alerts' %>
     <%end%>
   <div class="container">
        <%= yield %>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>